### ISSUE TITLE
The usage error code keeps popping up

### ISSUE THREAD

**Issue by Silphy1** [EtoileScintillante/lane-detection-cpp#1]
I keep getting the Usage error code how do i fix that?

**Comment by EtoileScintillante** [comment]
Hi, did you provide a path to the video when running the program? 

After compiling, when you want to run the program, you have to add a path to a video as a command line argument:
./Runner path-to-video-here

**Comment by Silphy1** [comment]
I'm new to c++ could you explain how to do that in detail? I'm on Microsoft visual studio

**Comment by EtoileScintillante** [comment]
The way I set up this project is that it can be easily built with cmake.

Do you have that installed? It's really convenient. 

I am a MacOS user myself so unfortunately I can't describe in detail how you should go about setting up cmake on Windows, but there are a lot of resources online.

**Comment by Silphy1** [comment]
i do have cmake

**Comment by EtoileScintillante** [comment]
Oh alright, that's good then.
So are you familiar with the command line?

**Comment by Silphy1** [comment]
Yes

**Comment by EtoileScintillante** [comment]
Okay so what you wanna do, assuming you cloned this repo, is open the command prompt and go to the repo and then, after building the program, type ./Runner path-to-video

Make sure to change that line to an actual path. So that could be for example videos/dashcam1.mp4

**Comment by Silphy1** [comment]
could you make a quick video i don't full understand if not don't worry about it

**Comment by EtoileScintillante** [comment]
Man I would if I was on Windows but like I said I am a Mac user, it works a bit different. Sorry!

**Comment by Silphy1** [comment]
its fine thanx for all the help!
